#!/usr/bin/env python3
import json
from random import shuffle
from sys import argv
def convert_mapping_json_to_infile(mapping_file, script_input_file):
    f = open(mapping_file)
    mapping = json.load(f)
    keys, values = map(list, zip(*mapping.items()))
    shuffle(keys)
    shuffle(values)
    txt = open(script_input_file, 'w')
    txt.write(json.dumps([keys, values]))
    txt.close()

if __name__ == '__main__':
    if len(argv) <= 2:
        exit(1)
    convert_mapping_json_to_infile(argv[1], argv[2])
