#!/usr/bin/env python3
import json
from sys import argv

def veritify(origin_file, mapping_file):
    of = open(origin_file)
    mf = open(mapping_file)
    of = json.load(of)
    mf = json.load(mf)
    if len(of) != len(mf):
        print('Size not match!!!')
        return
    for k in of:
        if of[k] != mf[k]:
            print('error')
    print('Match!!')

if __name__ == '__main__':
    if len(argv) <= 2:
        exit(1)

    veritify(argv[1], argv[2])
